title: The Orbital Space 
Knowledge Modeling Project
description: Ontology for Astronauitcs
creator: Robert J. Rovetto
name: Robert J. Rovetto
url: https://scholar.google.com/citations?user=jTkGEiMAAAAJ&hl=en&oi=sra
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
